[package]
name = "Tail"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
log = "0.4.28"
thiserror = "2.0.17"
utf8-read = "0.4.0"
